### ISSUE TITLE
Error while launch

### ISSUE THREAD

**Issue by saga111a** [OptiJuegos/education-cracked#2]
"Cannot find python38.dll Please re install" But I have python 3.8 in my PC.
 A u sure that it's really work?

**Comment by OptiJuegos** [comment]
You need to install Visual C++ 2015-2017-2019-2022 to Work

**Comment by FrannDzs** [comment]
> "Cannot find python38.dll Please re install" But I have python 3.8 in my PC. A u sure that it's really work?

Python is included in the installer, since the game can use code by blocks or using python, you don't need to download or install anything else, or add variables to the environment path. Maybe it's permissions issues because of the location where you installed the game.

**Comment by DT-L21** [comment]
Can someone describe how to use this exaclty i get the same error when i launch it outside the MCEE file location, and when i put it inside then it just doesnt do anything

**Comment by OptiJuegos** [comment]
You need to put the exe inside the minecraft education directory, if not you will have a lot of errores, because the game requieres more files than the exe has
