### ISSUE TITLE
Problem with source directory.

### ISSUE THREAD

**Issue by AgentKiller004** [OptiJuegos/education-cracked#4]
Apparently, C:\Program Files (x86)\Microsoft Studios is not a folder on my PC. Any takes? Edit: Also checked on my other drive which runs Windows, there is no Microsoft Studios folder.

**Comment by OptiJuegos** [comment]
Where is your game installed? you can search it easier by right clicking the shortcut of the game and clicking "open game location"

**Comment by OptiJuegos** [comment]
Then, you can paste the cracked exe there and open it

**Comment by AgentKiller004** [comment]
No, there is no option as "open game location" when right clicking, the only shortcut available is when I search for Minecraft Education.
![image_2024-02-13_232801674](https://github.com/OptiJuegos/education-cracked/assets/95495702/f7266dff-e736-4c85-9f36-be66c32fccc3)

**Comment by AgentKiller004** [comment]
I found the problem, I had to install it using the installer given on website.
