### ISSUE TITLE
1.20.60 support?

### ISSUE THREAD

**Issue by Weather-OS** [OptiJuegos/education-cracked#5]

**Comment by Weather-OS** [comment]
**Debug information**

Tested platforms: Windows (Native), Linux (Wine)
Results: Both produce the same result.

Crash reported at offset `0x0000000141C8E32F` at function `sub_141C8E2B0`, Binary file: `Minecraft.Windows.exe`
Crashed due to: `Lack of write access at memory address 0x00000000` => `MEMORY[0] = 0xDEADC0DE`

Tested "cracked" files: Debug UI mode/Login bypass using a "Play" button.

**Comment by Weather-OS** [comment]
**Further Analysis**

Looks like the game is trying to open a connection of some sort, Apparently this requires a signed user to be logged in in order to work properly. Jumping this segfault results in an infinite loading time at `Loading Resources...`. For the time being, current cracks don't work in this version. Use a legal copy of MC Edu.

**Comment by OptiJuegos** [comment]
Yeah, the new version of 1.20.60 crash while loading, this can be bypassed but the world doesn't ever load. just stucks at "loading resource packs" it seems to be an issue with the onedrive feature, probably it will get fixed when they put an option to turn it off

**Comment by OptiJuegos** [comment]
I tried to crack it, it doesn't work for me, maybe for you will do
https://cdn.discordapp.com/attachments/1090766119326994502/1208182382687948810/crak.zip?ex=65e25a86&is=65cfe586&hm=dea32cff3776d64874fc7465b2477e747c2eea362f7e1872dbf87149c3d62d8c&

**Comment by Weather-OS** [comment]
> I tried to crack it, it doesn't work for me, maybe for you will do https://cdn.discordapp.com/attachments/1090766119326994502/1208182382687948810/crak.zip?ex=65e25a86&is=65cfe586&hm=dea32cff3776d64874fc7465b2477e747c2eea362f7e1872dbf87149c3d62d8c&

Crashes before initialization, at offset `0x00CC5060`. Can you provide a patched 64-bit build instead?

**Comment by Weather-OS** [comment]
Addition of https://www.mediafire.com/file/frk7spx9rce6dt4/OptiCraft+1.21.0+BETA+By+OptiJuegos.7z/file makes this issue deprecated.
